name: color_canvas
description: "Unleash your inner interior designer with \\\"Paint Roller,\\\" the mobile-first app that transforms how you discover and visualize paint palettes, featuring real colors from leading brands like Sherwin-Williams, Benjamin Moore, and Behr."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^4.0.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  firebase_storage: ^13.0.0
  shared_preferences: ^2.0.0
  flutter_svg: ^2.0.0
  image: ^4.0.0
  path_provider: ^2.0.0
  share_plus: ^11.0.0
  flutter_colorpicker: ^1.0.0
  file_picker: '>=8.1.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/documents/
